name: bench
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - benchmark
  - cmake
  - python
  - jupyter
  - pandas
  - jupytext
  - tensorboard
  - pip
  - pip:
    - torch_tb_profiler
