name: bench
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - benchmark
  - cmake
  - python
  - jupyter
  - pandas
  - jupytext
  - tensorboard
  - pytorch
  - compilers
  - clang-format
  - pip
  - pip:
      - torch_tb_profiler
